name: Publish to PyPI

on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-*

jobs:
  release-pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - --version 1.1.8
          $HOME/.local/bin/poetry config virtualenvs.in-project true
      - name: Publish to PyPI
        run: $HOME/.local/bin/poetry build # publish --build
        #env:
        #  POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
