name: Test

on: [ push, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # colab runs on 3.7, 3.9 is the latest published version
        python-version: [ '3.7', '3.9' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - --version 1.1.8
          $HOME/.local/bin/poetry config virtualenvs.in-project true
      - uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
          #restore-keys: |
          #  poetry-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install depencies
        run: $HOME/.local/bin/poetry install -E alphafold
      - name: Run tests
        run: .venv/bin/pytest
      - name: Run CLI
        run: |
          .venv/bin/colabfold_batch --help
          .venv/bin/colabfold_search --help
          .venv/bin/colabfold_split_msas --help

